version: "3.8"

services:
  telegram_bot:
    build: .
    container_name: my_telegram_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=8426780934:AAH3B12akGlHF2G8v-JMCyGYK8Sx0Mn65f4
